"""
Kline (OHLC candle) data IO: save_klines / read_klines.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from pathlib import Path
from typing import Literal

from tradetropy.io._backends import (
    _detect_format, _resolve_write_format, _read, _write,
    _read_attrs, _write_hdf5_attrs,
)
from tradetropy.io._common import (
    _source_to_df_klines, _ts_to_datetime, _datetime_to_ts_ms,
)


def save_klines(
    data: "OhlcProxy | np.ndarray | pd.DataFrame",
    path: str | Path,
    format: 'Literal["csv", "parquet", "hdf5", "npz"] | None' = None,
    include_partial: bool = True,
    ts_format: Literal["iso", "ms", "s"] = "iso",
    hdf5_key: str = "data",
    compression: str = "snappy",
    metadata: "dict | None" = None,
) -> pd.DataFrame:
    """
    Save klines to file.

    Args:
        data: OhlcProxy, ndarray [N×6] or DataFrame with standard OHLC columns.
        path: Destination file path.
        format: Output format ('csv', 'parquet', 'hdf5', 'npz'). None (default)
            infers from the extension, falling back to 'npz'.
        include_partial: Include partial candle (partial=1) in OhlcProxy.
        ts_format: Timestamp format for CSV ('iso', 'ms', 's').
        hdf5_key: Key inside the HDF5 file.
        compression: Parquet compression method ('snappy', 'gzip', 'zstd', None).
        metadata: Optional dict of tradetropy metadata to store as HDF5 attrs.

    Returns:
        pd.DataFrame: The saved kline data as DataFrame.

    Example:
        save_klines(self.btc_1m, 'ohlc.npz')
        save_klines(self.btc_1m, 'ohlc.parquet', format='parquet')
        save_klines(self.btc_1m, 'session.h5', format='hdf5', hdf5_key='btc/1m')
    """
    from tradetropy.core.constants import OHLC_COLS, N_OHLC_COLS

    format = _resolve_write_format(path, format)
    df = _source_to_df_klines(data, N_OHLC_COLS, OHLC_COLS, include_partial)
    if format == "csv":
        df = _ts_to_datetime(df, ts_format)
    elif format != "npz":
        df = _ts_to_datetime(df, "ms")
    # npz keeps the raw millisecond 'ts' column (read_klines handles both).
    _write(df, path, format, hdf5_key, compression, metadata)
    if format == "hdf5" and metadata:
        _write_hdf5_attrs(Path(path), hdf5_key, metadata)
    return df


def read_klines(
    path: str | Path,
    symbol: "str | None" = None,
    timeframe: "str | int | None" = None,
    format: 'Literal["csv", "parquet", "hdf5", "npz"] | None' = None,
    hdf5_key: str = "data",
    col_datetime: str = "datetime",
    tick_size: float = 0.01,
    tick_value: float = 0.01,
    contract_size: float = 1.0,
    digits: int = 2,
    avg_spread: float = 0.0,
    volume_min: float = 0.01,
    volume_max: float = 100.0,
    volume_step: float = 0.01,
) -> "KlineData":
    """
    Read klines from file and return KlineData.

    Accepts external files (broker CSV) and files generated by save_klines().

    Required columns: datetime, open, high, low, close, volume
    Optional columns: turnover (filled with NaN if missing)

    Args:
        path: File path to read from.
        symbol: Trading symbol. If None, read from HDF5 attrs (saved by
            KlineData.save()). Required for CSV/Parquet or non-tradetropy files.
        timeframe: Candle interval. Accepts a timeframe string ('1m', '5m',
            '1h', '1d', etc.) or an integer number of milliseconds, parsed via
            parse_timeframe(). If None, read from HDF5 attrs.
        format: File format ('csv', 'parquet', 'hdf5'). None -> auto-detect.
        hdf5_key: Key inside HDF5 file.
        col_datetime: Datetime column name.
        tick_size: Minimum price move.
        tick_value: Value of one tick.
        contract_size: Size of contract.
        digits: Number of decimal places.
        volume_min: Minimum order volume.
        volume_max: Maximum order volume.
        volume_step: Minimum volume increment (lot step).

    Returns:
        KlineData: Kline data object.

    Example:
        klines = read_klines('ohlc.parquet', 'BTCUSDT', timeframe='1m')
        klines = read_klines('session.h5')  # all read from attrs
        klines = read_klines('bybit_export.csv', 'BTCUSDT', timeframe=60_000)
    """
    from tradetropy.core.constants import parse_timeframe
    from tradetropy.core.data_types import KlineData

    path    = Path(path)
    format  = format or _detect_format(path)

    if format in ("hdf5", "npz") and (symbol is None or timeframe is None):
        attrs = _read_attrs(path, format, hdf5_key)
        if symbol is None:
            symbol = attrs.get("tradetropy_symbol")
        if attrs.get("tradetropy_symbol") is not None:
            tick_size    = attrs.get("tradetropy_tick_size", tick_size)
            tick_value   = attrs.get("tradetropy_tick_value", tick_value)
            contract_size = attrs.get("tradetropy_contract_size", contract_size)
            digits       = attrs.get("tradetropy_digits", digits)
            avg_spread   = attrs.get("tradetropy_avg_spread", avg_spread)
            volume_min   = attrs.get("tradetropy_volume_min", volume_min)
            volume_max   = attrs.get("tradetropy_volume_max", volume_max)
            volume_step  = attrs.get("tradetropy_volume_step", volume_step)
            if timeframe is None:
                stored_interval = attrs.get("tradetropy_interval_ms")
                if stored_interval is not None:
                    timeframe = int(stored_interval)

    if symbol is None:
        raise ValueError(
            "symbol is required. Pass it explicitly or use a file saved by "
            "KlineData.save() with format='hdf5'."
        )

    if timeframe is None:
        raise ValueError(
            "read_klines() requires a timeframe (e.g. timeframe='5m' or "
            "timeframe=60_000). The file has no tradetropy_interval_ms attr "
            "(not saved by KlineData.save(), or saved before the timeframe "
            "was set) - pass timeframe explicitly to fix it going forward."
        )
    interval_ms = parse_timeframe(timeframe)

    df = _read(path, format, hdf5_key)

    # Discard partial candles if coming from save_klines()
    if "partial" in df.columns:
        df = (
            df[df["partial"] == 0]
            .drop(columns=["partial"])
            .reset_index(drop=True)
        )

    # Accept a raw 'ts' column (record path / _append_klines_hdf5) or a
    # human-readable 'datetime' column (save_klines csv), mirroring read_ticks.
    if "ts" in df.columns:
        ts_ms = df["ts"].to_numpy(dtype=np.int64)
        df    = df.drop(columns=["ts"])
    else:
        ts_ms = _datetime_to_ts_ms(df[col_datetime])
        df    = df.drop(columns=[col_datetime])

    cols_map = {c.lower(): c for c in df.columns}

    def _col(name: str, default: float = 0.0) -> np.ndarray:
        real = cols_map.get(name)
        return (
            df[real].to_numpy(dtype=np.float64)
            if real
            else np.full(len(df), default, dtype=np.float64)
        )

    data = np.column_stack([
        ts_ms,
        _col("open"), _col("high"), _col("low"), _col("close"),
        _col("volume"), _col("turnover", np.nan),
    ])

    return KlineData(
        symbol=symbol, data=data, timeframe=interval_ms,
        tick_size=tick_size, tick_value=tick_value,
        contract_size=contract_size, digits=digits,
        volume_min=volume_min, volume_max=volume_max,
        volume_step=volume_step,
    )
